name: Github Actions Demo
on: push
 
env:
  VAR1 : VAR1
  VAR2 : VAR2

jobs:
  hello-world-build :
    runs-on: ubuntu-latest
    env:
      VAR3 : Hi Ankit
      VAR4 : VAR2
    steps:
      - name: Hi
        run : echo ${VAR3}


  hello-world:
    runs-on: ubuntu-latest
    needs: [hello-world-build] #first the hello world build should run then this
    env:
      VAR3 : VAR1
      VAR4 : VAR2

    steps:
      - name: Simple JS Action
        uses: actions/hello-world-javascript-action@v1
        id: greet
        with:
          who-to-greet: "Ankit" # a variable accepted by the action
          
      - name: Error Step
        continue-on-error: true # rest of the steps should continue even if there is error in this step
        run: echhho $HI
    
      - name: Env Variables
        if : failure() #this step should continue if error in previous step
        env:
          VAR5 : VAR1
          VAR6 : VAR2
        run: |
          echo "${VAR1}"
          echo "${VAR2}"
          echo "${VAR3}"
          echo "${VAR4}"
          echo "${VAR5}"
          echo " ENV SECRET : ${{secrets.TEST_SECRET}}"

      
      - name: log time
        if : failure()
        run: echo "${{steps.greet.outputs.time}}"
      
      - name: List Files
        run: |
          pwd
          ls
       
      - name : Commit a Files
        run: |
          git init
          echo "========================================================================="
          git remote add origin "https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git" 
          echo "========================================================================="

          git config --global user.email "ankit.c7+1@gmail.com"
          git config --global user.name "ankit chauhan"

          echo "========================================================================="
          git fetch
          echo "========================================================================="
          git checkout main
          echo "========================================================================="
          git branch --set-upstream-to=origin/main
          echo "========================================================================="
          git pull
          echo "========================================================================="
          ls -a
          echo "========================================================================="
          echo $RANDOM >> random.txt
          echo "========================================================================="
          git add -A
          echo "========================================================================="
          git commit -m "random file"
          echo "========================================================================="
          git push 
          echo "========================================================================="

      - name: checkout
        uses: actions/checkout@v1
      
      - name: List Files Again
        run: |
          pwd
          ls
      - name: Print Job Context
        run: |
          echo "JOB_CONTEXT: $JOB_CONTEXT"
        env: 
          JOB_CONTEXT : ${{toJson(job)}}

